name: Framework tests
on: [push, pull_request]
env:
  GALAXY_TEST_DBURI: 'postgresql://postgres:postgres@localhost:5432/galaxy?client_encoding=utf8'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
        galaxy-branch: ['dev', 'master']
        metadata-strategy: ['directory']
        include:
          - python-version: '3.9'
            galaxy-branch: 'dev'
            metadata-strategy: 'extended'
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v5
        with:
          path: 'pulsar'
          persist-credentials: false
      - name: Checkout tools repo
        uses: actions/checkout@v5
        with:
          repository: galaxyproject/galaxy
          ref: ${{ matrix.galaxy-branch }}
          path: galaxy
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Build Pulsar wheel and replace Galaxy's requirements.
        run: python tools/replace_galaxy_requirements_for_ci.py
        working-directory: 'pulsar'
      - name: Run tests
        run: ./run_tests.sh --framework
        working-directory: 'galaxy'
        env:
          GALAXY_TEST_JOB_CONFIG_FILE: ../pulsar/test_data/test_job_conf.yaml
          GALAXY_CONFIG_OVERRIDE_METADATA_STRATEGY: ${{ matrix.metadata-strategy }}
      - uses: actions/upload-artifact@v5
        with:
          name: Framework test results (${{ matrix.galaxy-branch }} ${{ matrix.metadata-strategy  }} ${{ matrix.python-version }})
          path: 'galaxy/run_framework_tests.html'
