name: pulsar
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.7']
        tox-env: [lint, docs]
        include:
          - python-version: '3.14'
            tox-env: lint
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install tox
      run: pip install tox
    - name: Run lint
      run: tox -e ${{ matrix.tox-env }}
  mypy:
    name: MyPy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox-env: [mypy]
        python-version: ['3.14']
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install tox
      run: pip install tox
    - name: Setup pycurl
      run: sudo apt update; sudo apt install -y libxml2-dev libxslt1-dev libcurl4-openssl-dev openssh-server
    - name: Run tox
      run: tox -e ${{ matrix.tox-env }}
  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        tox-env: [test-ci, test-unit]
        python-version: ['3.7', '3.11']
        include:
        - tox-env: install_wheel
          python-version: '3.9'
    services:
      job-files:
        image: galaxy/simple-job-files:latest
        env:
          JOB_FILES_ROOT_DIRECTORY: /tmp
        ports:
          - '8000:8000'
        volumes:
          - '/tmp:/tmp:rw'
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install tox
      run: pip install tox
    - name: Run setup
      run: .ci/setup_tests.sh
    - name: Run tests
      run: . local_env.sh; tox -e ${{ matrix.tox-env }}
      env:
        PULSAR_TEST_KEY: "test_data/testkey"
        PULSAR_TEST_EXTERNAL_JOB_FILES_URL: "http://localhost:8000"
        PULSAR_TEST_EXTERNAL_JOB_FILES_DIRECTORY: "/tmp"
        TEST_WEBAPP_POST_SHUTDOWN_SLEEP: 1
  ## Can't get the following tests to work - they fall over on the containerized job not being able to
  ## connect to the host running the Pulsar server for file transfers in stage out/in.
  # tes-test:
  #   name: Run Tests
  #   runs-on: ubuntu-20.04
  #   strategy:
  #     matrix:
  #       include:
  #       - tox-env: test-funnel
  #         python-version: 3.7
  #   steps:
  #   - uses: actions/checkout@v5
  #     with:
  #       persist-credentials: false
  #   - uses: actions/setup-python@v6
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #       cache: pip
  #   - name: Set up Go 1.x
  #     uses: actions/setup-go@v2
  #     with:
  #       go-version: ^1.13
  #   - name: Pre-fetch required docker containers
  #     run: docker pull 'galaxy/pulsar-pod-staging:0.15.0.0' && docker pull 'conda/miniconda3'
  #   - name: Install tox
  #     run: pip install tox
  #   - name: Run tests
  #     run: PULSAR_TEST_INFRASTRUCTURE_HOST="_PLATFORM_AUTO_" FUNNEL_SERVER_TARGET=DEPLOY PULSAR_TES_SERVER_TARGET=http://localhost:8000/ tox -e ${{ matrix.tox-env }}
